apiVersion: v1
kind: Service
metadata:
  name: tetris-app-service

spec:
  type: NodePort

  selector:
    app: tetris-app

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
